# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./web

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: cp ./public/example.scene.yaml ./public/scene.yaml
    - name: Find and Replace
      uses: bluwy/substitute-string-action@v1
      id: sub
      with:
        _input-file: './public/scene.yaml'
        _format-key: '%%key%%'
        fair_url: 'https://fairos.fairdatasociety.org/v1/kv/entry/get?pod_name={fair_pod}&table_name={fair_kv}&key={z}_{x}_{y}'
    - name: Create .env file
      run: |
          touch .env
          echo REACT_APP_FAIROSHOST=https://fairos.fairdatasociety.org >> .env
          echo REACT_APP_DEFAULT_REGISTRY_REFERENCE=17dede7098cbd03b20d7d3e7091dc28fbcc0a7b264537312d80cdc714c1b727278a0056af2e3372260f501b38ab9f5f291fdda95c6fc01b4c878e234873b6660 >> .env
          cat .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: build
      run: yarn build
      env:
        CI: false
    - run: yarn deploy
