# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./web

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: cp ./public/example.scene.yaml ./public/scene.yaml &&  cp ./public/public-example.scene.yaml ./public/public-scene.yaml
    - run: ls -l
    - run: sed -i 's+fair_url+https://fairos-mainnet.fairdatasociety.org/v1/kv/entry/get?pod_name={fair_pod}\&table_name={fair_kv}\&key={z}_{x}_{y}+g' ./public/scene.yaml
    - name: Create .env file
      run: |
          touch .env
          echo REACT_APP_FAIROSHOST=https://fairos-mainnet.fairdatasociety.org/v1/ >> .env
          echo REACT_APP_DEFAULT_REGISTRY_REFERENCE=809be603371a60a3026e21e13dacc9704fb52b25580afec6c8da722829458ca1 >> .env
          cat .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: build
      run: yarn build
      env:
        CI: false
    - run: yarn deploy
